# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/105TEVtLAXove2euuIpdevPuiKK2Kaa53
"""



import math

def calcular_compra():
    """
    Calcula el subtotal, IGV y total a pagar por N productos.
    """
    TASA_IGV = 0.18

    print("--- Calculadora de Compra con IGV (18%) ---")

    # ENTRADA: Precio del producto
    try:
        precio_producto = float(input("Ingrese el precio unitario del producto: "))
        cantidad_comprada = int(input("Ingrese la cantidad de productos comprados: "))
    except ValueError:
        print("Error: Asegúrese de ingresar números válidos para el precio y la cantidad.")
        return

    if precio_producto < 0 or cantidad_comprada < 0:
        print("Error: El precio y la cantidad no pueden ser negativos.")
        return

    # PROCESO
    subtotal = precio_producto * cantidad_comprada
    igv_monto = subtotal * TASA_IGV
    total_a_pagar = subtotal + igv_monto

    # SALIDA: Mostrar resultados formateados a dos decimales
    print("\n--- RESUMEN DE LA COMPRA ---")
    print(f"Precio Unitario: {precio_producto:.2f}")
    print(f"Cantidad: {cantidad_comprada}")
    print("------------------------------")
    print(f"Subtotal (Base Imponible): {subtotal:.2f}")
    print(f"IGV ({TASA_IGV * 100}%): {igv_monto:.2f}")
    print(f"Total a Pagar: {total_a_pagar:.2f}")
    print("------------------------------")

if __name__ == "__main__":
    calcular_compra()